# Copied from http://brianbuccola.com/how-to-install-xmonad-and-xmobar-via-stack/
# https://github.com/cbiffle/xmonad-config/
#
# apt-get install libxft-dev libiw-dev libxml2-dev libghc-alsa-core-dev libxpm-dev libxrandr-dev
# libxss-dev
#
# stack install xmonad xmobar --flag xmobar:with_iwlib

resolver: lts-12.4

packages:
- '.'

extra-deps: []

flags: {}

extra-package-dbs: []
