#!/bin/bash

xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42 = Escape'

# Disable paste with middle click:
# https://askubuntu.com/questions/4507/how-do-i-disable-middle-mouse-button-click-paste
xmodmap -e 'pointer = 1 25 3 4 5 6 7 8 9'
