#!/bin/bash

set -x

# to install:
SOFTWARE=(
  atool
  automake
  build-essential
  cabal-install
  cmake
  git
  highlight
  htop
  inotify-tools
  keychain
  moreutils
  mosh
  mutt
  ncdu
  pandoc
  pass
  python
  python-dev
  rlwrap
  sqlite3
  stow
  sudo
  tig
  tmux
  tree
  urlview
  vim
  zsh
)

sudo apt-get install "${SOFTWARE[@]}"
